import React,{useState,useRef} from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {PaintBrush,Code, Coffee,Lightning,Leaf,Users,ArrowUpRight,ArrowsClockwise,Shuffle,Sparkle,Check} from '@phosphor-icons/react';
import {jobs,Reveal} from './components.jsx';
const interests=[{label:'Ideeën maken',icon:PaintBrush,id:'design',why:'Je krijgt energie van ideeën en vormgeving.'},{label:'Mensen blij maken',icon:Coffee,id:'coffee',why:'Je wilt iets betekenen voor de mensen om je heen.'},{label:'Dingen bouwen',icon:Code,id:'code',why:'Je wilt oplossingen maken en zien dat ze werken.'}];
const moods=[{label:'Rust en focus',icon:Leaf,explain:'Vraag bij een kennismaking naar ruimte voor focus.'},{label:'Samen knallen',icon:Users,explain:'Vraag hoe het team samenwerkt en ideeën deelt.'},{label:'Elke dag anders',icon:Lightning,explain:'Vraag hoeveel afwisseling er in een werkweek zit.'}];
export default function WorkVibe({launch}){const [interest,setInterest]=useState(null),[mood,setMood]=useState(null),[result,setResult]=useState(false);const reduce=useReducedMotion();const resultRef=useRef(null);const selected=interests.find(i=>i.id===interest);const job=jobs.find(j=>j.id===interest);
 function reveal(){setResult(true);requestAnimationFrame(()=>resultRef.current?.focus({preventScroll:true}));}
 function surprise(){setInterest(interests[Math.floor(Math.random()*interests.length)].id);setMood(moods[Math.floor(Math.random()*moods.length)].label);reveal();}
 return <section id="werkvibe" className="workvibe section-wrap"><Reveal><div className="vibe-heading"><span className="vibe-sticker"><Sparkle size={15}/> EVEN PROBEREN</span><h2>Wat is jouw <span>werkvibe?</span></h2><p>Geen lange vragenlijst. Twee keuzes, een nieuwe richting om te ontdekken.</p></div><div className="vibe-layout"><div className="vibe-questions"><fieldset><legend>Waar krijg jij energie van?</legend><div className="choice-row">{interests.map(({label,icon:Icon,id})=><motion.button key={id} whileHover={reduce?{}:{y:-4,rotate:id==='design'?-2:2}} whileTap={reduce?{}:{scale:.97}} aria-pressed={interest===id} onClick={()=>{setInterest(id);setResult(false);}}><Icon size={28} weight="light"/><span>{label}</span>{interest===id&&<Check size={15} className="choice-check"/>}</motion.button>)}</div></fieldset><fieldset><legend>Hoe ziet jouw fijne werkdag eruit?</legend><div className="mood-row">{moods.map(({label,icon:Icon})=><button key={label} aria-pressed={mood===label} onClick={()=>{setMood(label);setResult(false);}}><Icon size={17}/>{label}</button>)}</div></fieldset><div className="vibe-actions"><button className="button" disabled={!interest||!mood} onClick={reveal}>Ontdek mijn richting <ArrowUpRight size={19}/></button><button className="underlined" onClick={surprise}><Shuffle size={17}/>Verras me</button></div><p className="vibe-disclaimer">Je keuzes blijven in deze pagina. Geen profiel, geen registratie.</p></div><div className={`vibe-result ${result?'has-result':''}`} ref={resultRef} tabIndex={-1}>
 {result&&job?<motion.div key={`${interest}-${mood}`} initial={reduce?false:{opacity:0,y:16,rotate:2}} animate={{opacity:1,y:0,rotate:0}} transition={{type:'spring',stiffness:150,damping:20}}><div className="result-photo"><img src={`./${job.image}.webp`} alt={`Voorbeeldwerkplek voor ${job.title}`} loading="lazy"/><span className="result-spark" aria-hidden="true"><Sparkle size={34} weight="fill"/></span></div><div className="result-copy"><span className="functional-label">JOUW DEMORICHTING</span><h3 role="status">{job.title}</h3><p>{selected.why} {moods.find(m=>m.label===mood).explain}</p><button className="underlined" onClick={()=>launch(job.id)}>Bekijk mijn voorbeeld <ArrowUpRight size={18}/></button><small>Geen AI-score. Dit voorbeeld volgt uit jouw keuzes.</small></div></motion.div>:<div className="vibe-waiting"><div className="floating-tokens" aria-hidden="true"><PaintBrush size={33}/><Code size={40}/><Coffee size={33}/></div><h3>Jouw volgende<br/>“ja, dit dus.”</h3><p>Kies wat bij je past.<br/>Wij laten je een voorbeeld zien.</p><ArrowsClockwise size={23} weight="light"/></div>}
 </div></div></Reveal></section>;
}
